[package]
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
license = "MIT/Apache-2.0"
name = "client"
version = "0.1.0"
publish = false

[dependencies]
glium = "0.14.0"
base = { path = "../base" }
