[package]
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
license = "MIT/Apache-2.0"
name = "plantex-prep-server"
version = "0.1.0"

[dependencies]

[dependencies.plantex-prep-common]
path = "../common"
